#!/bin/sh
#
# $Id: fab,v 1.2 2002/06/08 03:40:20 timmy Exp $
#
# Script to perform "release" builds under MacOS X.

# clean any old build products
rm -f *.dmg
rm -f Cuppa.zip
rm -rf build/Cuppa.app

# now, perform deployment clean and build
pbxbuild clean
pbxbuild -buildstyle Deployment

# clean out excessive symbols and dev cruft from the bundle
strip build/Cuppa.app/Contents/MacOS/Cuppa
rm -f build/Cuppa.app/Contents/pbdevelopment.plist

# create a zip file of the results
zip -rv9 Cuppa.zip build/Cuppa.app/

# .end fab
